Feat: Manage department
chukwuma-azubuike/coza-workforce-app pull request #40
Opened 2023-05-14 13:01 UTC by rarumdj

2023-05-14 14:49 UTC, chukwuma-azubuike requested changes
Please include screenshots and confirm that the issue with the `goBack` navigation is working.

2023-05-14 14:49 UTC, chukwuma-azubuike commented on src/components/layout/skeleton.tsx
> +// </Stack>
You can as well delete this.

2023-05-14 14:49 UTC, chukwuma-azubuike commented on src/store/services/account.ts
> +    useGetCampusSummeryByCampusIdQuery,
Typographical error `useGetCampusSummeryByCampusIdQuery`, supposed to be `useGetCampusSummaryByCampusIdQuery`

2023-05-14 14:49 UTC, chukwuma-azubuike commented on src/views/app/Workforce-management/global-workforce.tsx
> +    const { data, isLoading, isSuccess, isFetching } = useGetCampusSummeryByCampusIdQuery(campus._id);
Typo fix as well

2023-05-14 14:49 UTC, chukwuma-azubuike commented on src/views/app/Workforce-management/global-workforce.tsx
> +    }));
You should memoize this for better performance.

2023-05-14 14:49 UTC, chukwuma-azubuike commented on src/views/app/Workforce-management/global-workforce.tsx
> +                </Center>
This should be a separate component for reusability.

2023-05-14 14:49 UTC, chukwuma-azubuike commented on src/views/app/Workforce-management/workforce-management.tsx
> +            setOptions({ title: `${campusUsersData.departmentName || 'Workforce Management'}` });
There is already a hook for this. Check `useScreenFocus`

2023-05-14 22:23 UTC, rarumdj commented
the back button is not working because of the implementation you did on the index file please help check it @chukwuma-azubuike

2023-05-15 08:11 UTC, chukwuma-azubuike approved these changes
LGTM

2023-05-15 08:11 UTC, merged